printf "MIN_PROFIT_BPS=9\nSTOP_LOSS_BPS=8\nTRAIL_ARM_BPS=9\nTRAIL_GIVEBACK_BPS=3\nMAX_HOLD_SEC=240\nPOLL_SEC=1\nUSE_TRAILING=1\n" > sniper_settings.1437
printf "DYNAMIC_TIMEOUT=TRUE\nMAX_SLIPPAGE_BPS=2.5\nSTALL_DETECTION=4\nMIN_LIQUIDITY_CHECK=TRUE\n" > tempo_vortex.1437
printf "T_BASE=240\nK_ENTROPY=0.05\nSTALL_THRESHOLD_BPS_PER_SEC=0.05\nF_A_SMOOTHING=0.96\nCALORIE_EFFICIENCY_EXIT=TRUE\nMIN_HOLD=45s\nMAX_HOLD=600s\n" > relativite_v2.1437
