#!/usr/bin/env bash
set -euo pipefail

cd /Users/christophe/ace777-test-day1

# V8.3 SYNAPSE
# - BETA entre en x3 pour valider l'aspiration
# - si PnL BETA > 0 apres 256ms, ALPHA x13 est injecte immediatement
# - sortie via VELOCITY_DECAY (freinage/inversion) sans attendre timeout

export TEST_TAG_OVERRIDE="MASTER_BASE_V8_3_SYNAPSE_7H30"
export RUN_SEC_OVERRIDE=27000

# Base de risque
export MOMENTUM_THRESHOLD="${MOMENTUM_THRESHOLD:-0.85}"
export ALPHA_REVENGE_MULT="${ALPHA_REVENGE_MULT:-1.618}"
export GLOBAL_STOP_USDT="${GLOBAL_STOP_USDT:--16.00}"
export STOP_LOSS_BPS="${STOP_LOSS_BPS:-16}"

# V8.3 Tension
export V8_RESONANCE_MODE=TRUE
export VOLATILITY_IMPULSE_THRESHOLD="${MOMENTUM_THRESHOLD}"
export VOLATILITY_IMPULSE_DT_MS=128
export V8_TENSION_MODE=TRUE
export IMPULSE_RESONANCE_WALL_DROP_PCT=5
export IMPULSE_RESONANCE_DT_MS=128
export IMPULSE_RESONANCE_DEPTH_LIMIT=20
export VACUUM_TENSION_THRESHOLD=0.85
export V8_TENSION_FORCE_ENTRY_THRESHOLD=3.5
export MOMENTUM_SLEEP_SEC=0.128
export V8_ASPIRATION_MASS_MULT=1.618
export V8_ASPIRATION_ANGLE_DEG=37.8

# Sortie dynamique prioritaire (cycles longs)
export FLUID_EXIT_ENABLED=TRUE
export FLUID_EXIT_BRAKE_BPS_S=0.02
export FLUID_EXIT_INVERT_BPS_S=-0.02
export V8_SHOCK_EXIT_ENABLED=TRUE
export V8_SHOCK_SPEED_EPS_BPS_S=0.0001

# Vide / stop global
export V8_VOID_LOCK_ENABLED=TRUE
export V8_VOID_STEP_SEC=16
export DUO_GLOBAL_STOP_HALT_RUN=TRUE

# Radar garde-fou a 0.85 pour eviter le calme plat
export RADAR_GATE=TRUE
export RADAR_MIN_CONF=0.85
export TREND_FILTER=FALSE

# BETA_SENTINEL x3
export BETA_MOMENTUM_THRESHOLD="${MOMENTUM_THRESHOLD}"
export BETA_STOP_LOSS_BPS="${STOP_LOSS_BPS}"
export BETA_FORCE_ENTRY_SIDE=AUTO
export BETA_POSITION_SIDE=BOTH
export BETA_LEVERAGE_TARGET=3
export BETA_LEVERAGE_RAMP_ENABLED=FALSE
export BETA_SENTINEL_MODE=TRUE
export BETA_SENTINEL_CHECK_MS=256
export BETA_SENTINEL_NEG_PNL_EXIT=TRUE
export BETA_SENTINEL_TRUE_VACUUM_MIN_PNL=0.00000001

# ALPHA_STRIKE x13 sur TRUE_VACUUM
export ALPHA_DUO_MODE=TRUE
export DUO_HUNTER_REQUIRE_TRUE_VACUUM=TRUE
export ALPHA_FORCE_ENTRY_SIDE=AUTO
export ALPHA_RADAR_GATE=FALSE
export ALPHA_TREND_FILTER=FALSE
export ALPHA_MOMENTUM_THRESHOLD=0.01
export ALPHA_LEVERAGE_TARGET=13
export ALPHA_LEVERAGE_RAMP_ENABLED=TRUE
export ALPHA_LEVERAGE_RAMP_START=13
export ALPHA_LEVERAGE_RAMP_END=13
export ALPHA_LEVERAGE_RAMP_CYCLES=1
export ALPHA_STOP_LOSS_BPS="${STOP_LOSS_BPS}"

echo "=== V8.3 SYNAPSE === objectif: stabilite 77 USDT/jour (cible), non garantie."

exec ./launch_test_duo_harmonic_5_8_13_6h.sh
