print -P ""
print -P "%F{magenta}╔════════════════════════════════════════════════════════╗%f"
print -P "%F{cyan}║%f                                                        %F{cyan}║%f"
print -P "%F{cyan}║%f   %F{magenta}◆%f %F{cyan}V E I L L E%f  %F{magenta}·%f  %F{green}P U N K%f  %F{magenta}·%f  %F{cyan}2 0 2 6%f   %F{magenta}◆%f   %F{cyan}║%f"
print -P "%F{cyan}║%f                                                        %F{cyan}║%f"
print -P "%F{magenta}╠════════════════════════════════════════════════════════╣%f"
print -P "%F{cyan}║%f  %F{8}cold path · tweets · bullshit check · pas de fills%f  %F{cyan}║%f"
print -P "%F{cyan}║%f  %F{green}inbox/%f raw   %F{cyan}│%f  %F{green}out/%f digests   %F{cyan}│%f  %F{magenta}NO%f GO_USINE     %F{cyan}║%f"
print -P "%F{magenta}╚════════════════════════════════════════════════════════╝%f"
print -P "%F{green}  → check \"url-ou-texte\"%f  %F{8}→ Obsidian Swarm_Bus/Punk/ + contexte%f"
print -P "%F{8}  aide:%f %F{cyan}veille-help%f"
print -P ""
